import { useNavigate } from "react-router-dom";
import TeamMemberCard from "../Components/TeamMemberCard";
import "./Landing.css";

export default function Landing() {
  const navigate = useNavigate();

  return (
    <div className="landing">
      <div className="landing-grid">
        {/* LEFT: About + team cards */}
        <section className="panel">
          <h2 className="panel-title">Meet the Team</h2>
          <div className="stack">
            <TeamMemberCard name="Aadi" role="Mascot" />
            <TeamMemberCard name="Jacob" role="Front-End Architect" />
            <TeamMemberCard name="Yousef" role="Electrical Engineer" />
            <TeamMemberCard name="Josh" role="Backend Developer" />
          </div>
        </section>

        {/* MIDDLE: Big logo + login card */}
        <section className="center">
          <div className="logo">V</div>

          <button className="chatBtn" onClick={() => navigate("/chatUnlogged")}>
            Chat
          </button>

          <button className="leaderboardBtn" onClick={() => navigate("/login")}>
            Join the Shame Leaderboard
          </button>
        </section>

        {/* RIGHT: Description */}
        <section className="panel">
          <h2 className="panel-title">Description</h2>
          <div className="descLines">
            <p>
              Varuna is an AI sustainability tracker designed to measure the
              real-world environmental impact of large language model usage. By
              analyzing token consumption, Varuna estimates water usage,
              electricity demand, and CO₂ emissions generated by AI workloads.
            </p>

            <p>
              The platform provides real-time session insights alongside
              cumulative lifetime metrics, enabling teams to monitor trends,
              optimize usage efficiency, and make data-driven decisions to
              reduce their carbon footprint.
            </p>

            <p>
              Built with transparency and accessibility in mind, Varuna offers a
              clean dashboard experience that helps organizations integrate
              sustainability directly into their development workflows and AI
              deployment strategies.
            </p>
          </div>
          <h3 className="leaderboardTitle">Shame Leaderboard (Top 3)</h3>

          <ul className="leaderboard">
            <li className="lbCard">
              <img className="lbImg" src="/placeholder1.png" alt="Alice" />
              <div className="lbText">
                <strong>#1 Alice</strong>
                <span>CO₂: 12.4 kg • Water: 58 L • </span>
              </div>
            </li>

            <li className="lbCard">
              <img className="lbImg" src="/placeholder2.png" alt="Bob" />
              <div className="lbText">
                <strong>#2 Bob</strong>
                <span>CO₂: 9.8 kg • Water: 44 L</span>
              </div>
            </li>

            <li className="lbCard">
              <img className="lbImg" src="/placeholder3.png" alt="Charlie" />
              <div className="lbText">
                <strong>#3 Charlie</strong>
                <span>CO₂: 7.1 kg • Water: 36 L</span>
              </div>
            </li>
          </ul>
        </section>
      </div>
    </div>
  );
}
