import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import TeamMemberCard from "../Components/TeamMemberCard";
import "./Landing.css";

export default function Landing() {
  const navigate = useNavigate();
  const [leaders, setLeaders] = useState([]);

  useEffect(() => {
    const loadTop3 = async () => {
      try {
        const res = await fetch("http://127.0.0.1:8000/api/leaderboard", {
          credentials: "include",
        });
        const data = await res.json();
        // backend returns { leaders: [...] }
        setLeaders((data.leaders || []).slice(0, 3));
      } catch (err) {
        console.error("Failed to load leaderboard:", err);
        setLeaders([]);
      }
    };

    const intervalId = setInterval(loadTop3, 30000);
    return () => clearInterval(intervalId);
  }, []);

  return (
    <div className="landing">
      <div className="landing-grid">
        {/* LEFT: About + team cards */}
        <section className="panel">
          <h2 className="panel-title">Meet the Team</h2>
          <div className="stack">
            <TeamMemberCard name="Aadi" role="Mascot" />
            <TeamMemberCard name="Jacob" role="Front-End Architect" />
            <TeamMemberCard name="Yousef" role="Electrical Engineer" />
            <TeamMemberCard name="Josh" role="Backend Developer" />
          </div>
        </section>

        {/* MIDDLE: Big logo + login card */}
        <section className="center">
          <div className="logo">V</div>

          <button className="chatBtn" onClick={() => navigate("/chatUnlogged")}>
            Chat
          </button>

          <button className="leaderboardBtn" onClick={() => navigate("/login")}>
            Join the Shame Leaderboard
          </button>
        </section>

        {/* RIGHT: Description */}
        <section className="panel">
          <h2 className="panel-title">Description</h2>
          <div className="descLines">
            <p>
              Varuna is an AI sustainability tracker designed to measure the
              real-world environmental impact of large language model usage. By
              analyzing token consumption, Varuna estimates water usage,
              electricity demand, and CO₂ emissions generated by AI workloads.
            </p>

            <p>
              The platform provides real-time session insights alongside
              cumulative lifetime metrics, enabling teams to monitor trends,
              optimize usage efficiency, and make data-driven decisions to
              reduce their carbon footprint.
            </p>

            <p>
              Built with transparency and accessibility in mind, Varuna offers a
              clean dashboard experience that helps organizations integrate
              sustainability directly into their development workflows and AI
              deployment strategies.
            </p>
          </div>

          <h3 className="leaderboardTitle">Shame Leaderboard (Top 3)</h3>

          <ul className="leaderboard">
            {leaders.length === 0 ? (
              <li className="lbCard">
                <div className="lbText">
                  <strong>No leaderboard yet</strong>
                  <span>Run a prompt to generate stats.</span>
                </div>
              </li>
            ) : (
              leaders.map((user, index) => (
                <li className="lbCard" key={user.id || index}>
                  {/* keep the same visual structure you had */}
                  <img
                    className="lbImg"
                    src={photo}
                    alt={user.username}
                    loading="lazy"
                    onError={(e) => {
                      // prevent infinite error loops that can cause flicker
                      e.currentTarget.onerror = null;
                      e.currentTarget.src = photo;
                    }}
                  />
                  <div className="lbText">
                    <strong>
                      #{index + 1} {user.username}
                    </strong>
                    <span>
                      CO₂: {user.metrics?.co2_consumption ?? 0} • Water:{" "}
                      {user.metrics?.h2o_consumption ?? 0} • Energy:{" "}
                      {user.metrics?.wh_consumption ?? 0}
                    </span>
                  </div>
                </li>
              ))
            )}
          </ul>
        </section>
      </div>
    </div>
  );
}
